[package]
name = "search"
version = "0.1.0"
edition = "2024"

[dependencies]
fst = { version = "0.4", features = ["levenshtein"] }
itertools = "0.14.0"
once_cell = "1.21.3"
owo-colors = "4.2.0"
regex = "1.11.1"
roaring = "0.10.12"
walkdir = "2.5.0"
